name: 'PR Dependency Check'
description: 'Verify PR dependencies are merged or closed'
author: 'Ferry Cools'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  custom-domains:
    description: 'Space-delimited list of custom domains where issues may be found'
    required: false
    default: ''
outputs:
  has-dependencies:
    description: 'Whether any dependencies were found'