name: 'Dependency Checker'
description: 'Checks if dependencies or dependents are defined for an issue and if they are merged or closed.'
author: 'Ferry Cools'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'node20'
  main: 'dist/main.js'
inputs:
  phrases:
    description: 'Pipe-separated list of key phrases to identify dependency declarations.'
    required: false
    default: 'depends on|blocked by'
  blocked_label:
    description: 'Label to add to an issue when unresolved dependencies are defined.'
    required: false
    default: 'blocked'
  blocking_label:
    description: 'Label to add to an issue when unresolved dependents are defined.'
    required: false
    default: 'blocking'
outputs:
  has-dependencies:
    description: 'Whether any dependencies were found'
